[project]
name = "star-tarven-simulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhinanertui", email = "zhinanertui@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
star-tarven-simulator = "star_tarven_simulator:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mpyq>=0.2.5",
    "pytest>=9.1.1",
]
